FROM discourse/discourse:latest

# Set environment variables
ENV DISCOURSE_HOSTNAME=${DISCOURSE_HOSTNAME}
ENV DISCOURSE_DEVELOPER_EMAILS=${DISCOURSE_DEVELOPER_EMAILS}
ENV DISCOURSE_SMTP_ADDRESS=${DISCOURSE_SMTP_ADDRESS}
ENV DISCOURSE_SMTP_PORT=${DISCOURSE_SMTP_PORT}
ENV DISCOURSE_SMTP_USER_NAME=${DISCOURSE_SMTP_USER_NAME}
ENV DISCOURSE_SMTP_PASSWORD=${DISCOURSE_SMTP_PASSWORD}
ENV DISCOURSE_SMTP_ENABLE_START_TLS=${DISCOURSE_SMTP_ENABLE_START_TLS}
ENV DISCOURSE_SMTP_DOMAIN=${DISCOURSE_SMTP_DOMAIN}

# Copy configuration files
COPY discourse.conf /var/discourse/config/discourse.conf

# Expose port
EXPOSE 80

# Start Discourse
CMD ["/var/discourse/launcher", "start", "app"] 